# Generated by Django 5.2.5 on 2025-10-05 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_choice_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pub_dete',
            new_name='pub_date',
        ),
    ]
