# Generated by Django 5.2.5 on 2025-10-05 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_pub_dete_question_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='votex',
            new_name='votes',
        ),
    ]
